openCaseMaster/ViewModels/application/applicationModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace openCaseMaster.ViewModels
{
    public class applicationModel
    {
        [Required]
        public int id { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "{0} 必须至少包含 {2} 个字符。", MinimumLength = 1)]
        [Display(Name = "app名")]
        public string name { get; set; }


        [Display(Name = "robotium脚本")]
        public string runApkName { get; set; }

        [Display(Name = "安卓package")]
        public string package { get; set; }

        [Display(Name = "安卓mainActiviy")]
        public string mainActiviy { get; set; }


        [Display(Name = "ios-package")]
        public string package2 { get; set; }

        [Display(Name = "清理缓存")]
        public bool? isClear { get; set; }
    
    }

    public class applicationListModel
    {
      

        public int total { get; set; }

        public List<applicationModel> rows { get; set; }

    }
}

openCaseMaster/Controllers/applicationController.cs
using openCaseMaster.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using openCaseMaster.ViewModels;


namespace openCaseMaster.Controllers
{
    [Authorize(Roles="admin")]
    public class applicationController : Controller
    {
        // GET: application
        public ActionResult Index()
        {
            return View();
        }

        // GET: application
        public ActionResult apps(int page, int rows)
        {

            QCTESTEntities QC_DB = new QCTESTEntities();

            var us = from t in QC_DB.M_application
                     orderby t.ID
                     select new applicationModel
                     {
                         id = t.ID,
                         name = t.name,
                         runApkName = t.runApkName,
                         package = t.package,
                         mainActiviy = t.mainActiviy,
                         package2 = t.package2,
                         isClear = t.isClear
                     };

            applicationListModel md = new applicationListModel();
            md.total = us.Count();

            md.rows = us.Skip(rows * (page - 1)).Take(rows).ToList();


            return Json(md, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult edit(int id)
        {

            QCTESTEntities QC_DB = new QCTESTEntities();
            var app = QC_DB.M_application.First(t => t.ID == id);

            var md = new applicationModel();
            md.id = app.ID;
            md.isClear = app.isClear;
            md.mainActiviy = app.mainActiviy;
            md.name = app.name;
            md.package = app.package;
            md.package2 = app.package2;
            md.runApkName = app.runApkName;


            return Json(md, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public string edit(int id,applicationModel md)
        {
            if (!ModelState.IsValid)
            {
                Response.StatusCode = 500;
                return "非法提交";
            }
            QCTESTEntities QC_DB = new QCTESTEntities();


            var app = QC_DB.M_application.First(t => t.ID == id);
            app.isClear = md.isClear;
            app.mainActiviy = md.mainActiviy;
            app.name = md.name;
            app.package = md.package;
            app.package2 = md.package2;
            app.runApkName = md.runApkName;

            QC_DB.SaveChanges();
            return null;
        }


        [HttpPost]
        public ActionResult add(applicationModel md)
        {
            if (!ModelState.IsValid)
            {
                Response.StatusCode = 500;
                ViewBag.err = "非法提交";
                return View("Error");
            }
            QCTESTEntities QC_DB = new QCTESTEntities();


            var app =  new M_application();
            app.isClear = md.isClear;
            app.mainActiviy = md.mainActiviy;
            app.name = md.name;
            app.package = md.package;
            app.package2 = md.package2;
            app.runApkName = md.runApkName;

            QC_DB.M_application.Add(app);

            QC_DB.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

openCaseMaster/Views/application/Index.cshtml
@section Scripts {
    @Styles.Render("~/Content/easyui")
    @Scripts.Render("~/bundles/easyui")
}
@{
    ViewBag.Title = "app管理";
}

<table id="appsTable" class="easyui-datagrid" title="app管理"
       data-options="rownumbers:true,singleSelect:true,toolbar:'#Tool',
       pageSize: 10,pagination:true,method:'get',url:'apps',onDblClickRow:TableDblClick,
       collapsible:true">

    <thead>
        <tr>
            <th data-options="field:'name',width:140">app</th>
            <th data-options="field:'runApkName',width:140">robotium脚本</th>
            <th data-options="field:'package',width:200">安卓package</th>
            <th data-options="field:'mainActiviy',width:300">安卓mainActiviy</th>
            <th data-options="field:'package2',width:200">ios-package</th>
            <th data-options="field:'isClear',width:140,align:'center'">清理缓存</th>
        </tr>
    </thead>

</table>

<div id="Tool" style="padding:5px;height:auto">

    <a class="easyui-linkbutton" href="javascript:void(0);" title="新增" data-options="plain:true,iconCls:'icon-add'" data-toggle="modal" 
   data-target="#addModal">新增</a>

</div>


<!-- 模态框（Modal） -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" data-backdrop="static"
     aria-labelledby="编辑" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"
                        data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">
                    编辑app
                </h4>
            </div>
            <div class="modal-body" style="padding:10px 50px;">
                @Html.Partial("_edit", new openCaseMaster.ViewModels.applicationModel(), new ViewDataDictionary { { "id", "editForm" } })

            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>



<!-- 模态框（Modal） -->
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" data-backdrop="static"
     aria-labelledby="编辑" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"
                        data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">
                    新增app
                </h4>
            </div>
            <div class="modal-body" style="padding:10px 50px;">
                @Html.Partial("_add", new openCaseMaster.ViewModels.applicationModel(), new ViewDataDictionary { { "id", "addForm" } })

            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>

<script>


    $("#editForm").submit(function () {
        if (!$(this).valid()) return false;
        jQuery.ajax({
            url: $(this).attr("action"),
            data: $(this).serialize(),
            type: "POST",
            success: function (responseText) {
                $("#editModal").modal("hide");
                $('#appsTable').datagrid('reload');
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {

                alert("发生错误,请联系管理员");
            },
        });
        return false;
    })


    function editDevice(id) {
        $.messager.progress({ title: '请稍后', msg: '加载中...' });

        $.get('edit/' + id, function (data) {
            $("#editModal").fillData(data);
            $("#editModal").modal("show");
            $.messager.progress('close');
        });

        //$("#myModal .modal-content").load('edit/' + id, function () {
        //    $.messager.progress('close');
        //    $("#myModal").modal("show");
        //});
    }

    function TableDblClick(rowIndex, rowData) {
        editDevice(rowData.id)
    }

    function addDevice() {
        alert("请联系管理员");

    }

    function deleteDevice() {
        alert("请联系管理员");

    }


</script>

openCaseMaster/Views/application/_add.cshtml
@using openCaseMaster.Models;
@using openCaseMaster.ViewModels;
@model  applicationModel



@using (Html.BeginForm("add", "application", FormMethod.Post, new { @class = "form-horizontal", id = ViewData["id"] }))
{
    @Html.HiddenFor(m => m.id)
    <div class="form-group">
        @Html.LabelFor(m => m.name, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextBoxFor(m => m.name, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.runApkName, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextBoxFor(m => m.runApkName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.package, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextBoxFor(m => m.package, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.mainActiviy, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextBoxFor(m => m.mainActiviy, new { @class = "form-control" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(m => m.package2, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextBoxFor(m => m.package2, new { @class = "form-control" })
        </div>
    </div>


    List<SelectListItem> cmpyID = new List<SelectListItem>();
    cmpyID.Add(new SelectListItem() { Text = "不清理", Value = "false", Selected = Model.isClear != true });
    cmpyID.Add(new SelectListItem() { Text = "清理", Value = "true", Selected = Model.isClear == true });


    <div class="form-group">
        @Html.LabelFor(m => m.isClear, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.DropDownListFor(m => m.isClear, cmpyID, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-4 col-md-8">
            <input type="submit" value="修改" class="btn btn-default" />
        </div>
    </div>
}

openCaseMaster/Views/application/_edit.cshtml
@using openCaseMaster.Models;
@using openCaseMaster.ViewModels;
@model  applicationModel



@using (Html.BeginForm("edit", "application", FormMethod.Post, new { @class = "form-horizontal", id = ViewData["id"] }))
{
    @Html.HiddenFor(m => m.id)
    <div class="form-group">
        @Html.LabelFor(m => m.name, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextBoxFor(m => m.name, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.runApkName, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextBoxFor(m => m.runApkName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.package, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextBoxFor(m => m.package, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.mainActiviy, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextBoxFor(m => m.mainActiviy, new { @class = "form-control" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(m => m.package2, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextBoxFor(m => m.package2, new { @class = "form-control" })
        </div>
    </div>

    
        List<SelectListItem> cmpyID = new List<SelectListItem>();
        cmpyID.Add(new SelectListItem() { Text = "不清理", Value = "false",Selected = Model.isClear!=true });
        cmpyID.Add(new SelectListItem() { Text = "清理", Value = "true", Selected = Model.isClear == true });
        
    
    <div class="form-group">
        @Html.LabelFor(m => m.isClear, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.DropDownListFor(m => m.isClear, cmpyID, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-4 col-md-8">
            <input type="submit" value="修改" class="btn btn-default" />
        </div>
    </div>
}